version: '3.2'

services:
  web:
    container_name: IOT
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iot
      - POSTGRES_DB=CBG_DB
      
  telegram:
    container_name: tele_bot
    build: ./tele_bot
    volumes:
      - ./tele_bot/:/usr/src/tele_bot
    ports:
      - 8001:8001
    env_file:
      - ./.env.dev  

volumes:
  postgres_data: