# Generated by Django 4.1.1 on 2023-03-25 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBG_Image',
            fields=[
                ('Image_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='CBG_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='CBG_Food_Record',
            fields=[
                ('Record_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Before_CBG_Reading', models.FloatField(blank=True, default=0)),
                ('Before_CBG_Measurement', models.CharField(blank=True, default='', max_length=5)),
                ('Before_CBG_Uploaded_At', models.DateTimeField(blank=True, null=True)),
                ('Food_Name', models.CharField(blank=True, default='', max_length=50)),
                ('Food_Calorie', models.FloatField(blank=True, default=0)),
                ('Food_Carb', models.FloatField(blank=True, default=0)),
                ('Food_Sugar', models.FloatField(blank=True, default=0)),
                ('Food_Fibre', models.FloatField(blank=True, default=0)),
                ('Food_Uploaded_At', models.DateTimeField(blank=True, null=True)),
                ('After_CBG_Reading', models.FloatField(blank=True, default=0)),
                ('After_CBG_Measurement', models.CharField(blank=True, default='', max_length=5)),
                ('After_CBG_Uploaded_At', models.DateTimeField(blank=True, null=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
