# Generated by Django 4.1.1 on 2023-03-20 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBG_Reading',
            fields=[
                ('Reading_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Image', models.ImageField(blank=True, upload_to='Uploaded_Images/CBG_Images/')),
                ('Reading', models.FloatField(blank=True, default=0)),
                ('Measurement', models.CharField(blank=True, default='', max_length=5)),
                ('Reading_Uploaded_At', models.DateTimeField(blank=True, null=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
