# Generated by Django 4.1.1 on 2023-03-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbg_reading',
            name='Reading',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cbg_reading',
            name='Image',
            field=models.ImageField(default='empty.jpg', upload_to='Uploaded_Images/CBG_Images/'),
        ),
    ]
